local req_submodule = require('v.utils.wrappers').get_require_submodule('v.mappings')

-- req_submodule('unmappings')
req_submodule('basic')
req_submodule('basic_macos')
req_submodule('navigate')
req_submodule('window')
req_submodule('quickfix')
req_submodule('search')
req_submodule('extra')
req_submodule('clipboard')
req_submodule('cmdline')
req_submodule('terminal')
req_submodule('grep')
req_submodule('open')
req_submodule('register')
